### PR TITLE
Replace mod standard in favor of standard.

### PR DESCRIPTION
**Pull request by fiveisprime**
No more mod-standard (or worrying about the eslint peer dependency); just pure, standard, ASI goodness.

### CODE REVIEW

**Comment by jackboberg** [comment]
To be fair, you are not replacing `mod-standard` (since it also solves the peer-dependency issue), you are replacing a custom eslint setup that used `eslint-config-modulus`..that said:

`standard`‼️

:shipit:

**Comment by fiveisprime** [comment]
Oh right, I never pushed the `mode-standard` branch.. lol

**Comment by theworkflow** [comment]
👍

**Comment by fiveisprime** [comment]
FYI merging this is going to break the build for all other PRs 💃

**Pull request merged**
