### PR TITLE
Add --server-only option

### LINKED ISSUE #179: --server only
I think you need to modify the build script on your meteor deploy so that the build does -- server-only

If you do that it will skip the mobile builds but retain the parts that we need if we are targeting mobiles and life will be Awesome

### PR DESCRIPTION
**Pull request by fiveisprime**
Allows users to demeteorize only web portion of the application.

Closes #179

### CODE REVIEW

**Comment by fiveisprime** [comment]
Disabled the lint because it was all messed up and standard doesn't work with this project.

**Comment by franvarney** [comment]
👍

**Comment by harlanj** [comment]
:+1:

**Comment by robertBrown** [comment]
Accepting new PR's?

-----Original Message-----

**Comment by sjmcdowall** [comment]
@robertBrown -- I haven't seen them ever NOT accept / look at PR requests.. ??

**Comment by fiveisprime** [comment]
Of course we're accepting PRs, it's open source!

**Comment by jackboberg** [comment]
tested in staging build images for modulus, worked like a charm :bangbang:

**Pull request merged**
